# This file was generated by GoReleaser. DO NOT EDIT.
cask "astro" do
  name "astro"
  desc "a habit tracker for your terminal with a GitHub style activity graph"
  homepage "https://github.com/joaofnds/astro"
  version "0.0.40"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "astro"

  on_macos do
    on_intel do
      url "https://github.com/joaofnds/astro/releases/download/#{version}/astro_#{version}_darwin_amd64.tar.gz"
      sha256 "ac9d97ba964f7b04dd6f97ed06f0d1b04e87f3a140d4a36c75d694ba256d73e6"
    end
    on_arm do
      url "https://github.com/joaofnds/astro/releases/download/#{version}/astro_#{version}_darwin_arm64.tar.gz"
      sha256 "e7faae7eef2520446b7fb825b12a0611500f2f76ecda3111cbcc0d449b635da0"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/joaofnds/astro/releases/download/#{version}/astro_#{version}_linux_amd64.tar.gz"
      sha256 "98d6d5cea62d7e6e2ad2059b66b24402cbdd192e161d30746fbcfcd1deef4499"
    end
    on_arm do
      url "https://github.com/joaofnds/astro/releases/download/#{version}/astro_#{version}_linux_arm64.tar.gz"
      sha256 "7b72dac4b457a9b177c54ba717384df1ea4696ee82bb4aeee9b9fdbf41c4d5c6"
    end
  end

  # No zap stanza required
end
