# This file was generated by GoReleaser. DO NOT EDIT.
cask "astro" do
  version "0.0.41"

  on_macos do
    on_intel do
      sha256 "8e0f05c599cc4fd94fb84fd6486c368668f6b4cab848bce1670350f2a5087b30"
      url "https://github.com/joaofnds/astro/releases/download/#{version}/astro_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "898f4abda41b9ae7547db4494f636dd4608be3e70181070a438473964017b8ab"
      url "https://github.com/joaofnds/astro/releases/download/#{version}/astro_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "ada5c54ba289801d8377d746a5a829ff647d2a82a38cca65b83ae7d5d38bd67f"
      url "https://github.com/joaofnds/astro/releases/download/#{version}/astro_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "9108e38042f082a20ece8f2c8346b2485404dce655bf1cee980a0d179bd12f08"
      url "https://github.com/joaofnds/astro/releases/download/#{version}/astro_#{version}_linux_arm64.tar.gz"
    end
  end

  name "astro"
  desc "a habit tracker for your terminal with a GitHub style activity graph"
  homepage "https://github.com/joaofnds/astro"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "astro"

  # No zap stanza required

end
