# This file was generated by GoReleaser. DO NOT EDIT.
cask "astro" do
  version "0.0.43"

  on_macos do
    on_intel do
      sha256 "6a9258f47033f3b8af6b1cb5068dd0d1dc64c0aa3fd631d6fb13c0ab500dfa82"
      url "https://github.com/joaofnds/astro/releases/download/#{version}/astro_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "23a244f835fc740564d6a8139414c1df3f3eb01e1ef32a54914bad711a59be71"
      url "https://github.com/joaofnds/astro/releases/download/#{version}/astro_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "a36a5de765a53fb83519645bf63380371ea4803794bb9de45776879330144f75"
      url "https://github.com/joaofnds/astro/releases/download/#{version}/astro_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "2d664830b0e6cabc9ae3b0697c692d7d462bcf2cdd0b9a2915fd17d9cd6714e2"
      url "https://github.com/joaofnds/astro/releases/download/#{version}/astro_#{version}_linux_arm64.tar.gz"
    end
  end

  name "astro"
  desc "a habit tracker for your terminal with a GitHub style activity graph"
  homepage "https://github.com/joaofnds/astro"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "astro"

  # No zap stanza required

end
