# Generated by joaofnds/trunk release workflow. DO NOT EDIT.
cask "trunk@0.52.0" do
  version "0.52.0"

  on_intel do
    sha256 "35cd604a8ba9128486909a58412a9c90453e3c1e989b46a874de8e8a66947f8d"
    url "https://github.com/joaofnds/trunk/releases/download/v0.52.0/Trunk_0.52.0_x64.dmg"
  end
  on_arm do
    sha256 "fe81a82c6668e957345e75f78846d57c21e04983689895f911305f61220579ab"
    url "https://github.com/joaofnds/trunk/releases/download/v0.52.0/Trunk_0.52.0_aarch64.dmg"
  end

  name "Trunk"
  desc "Desktop Git GUI"
  homepage "https://github.com/joaofnds/trunk"

  app "Trunk.app"
  binary "#{appdir}/Trunk.app/Contents/MacOS/trunk"

  postflight do
    system_command "/usr/bin/xattr",
                   args: ["-cr", "#{appdir}/Trunk.app"]
  end

  zap trash: [
    "~/Library/Application Support/com.joaofnds.trunk",
    "~/Library/Caches/com.joaofnds.trunk",
    "~/Library/WebKit/com.joaofnds.trunk",
  ]
end
