# Generated by joaofnds/trunk release workflow. DO NOT EDIT.
cask "trunk@0.47.5" do
  version "0.47.5"

  on_intel do
    sha256 "bd1db3a797cce57d19a8006e49dc839f86d4d2c4a50f20509a8d3a80a86d907f"
    url "https://github.com/joaofnds/trunk/releases/download/v0.47.5/Trunk_0.47.5_x64.dmg"
  end
  on_arm do
    sha256 "ea14996857f9dab32556ed6c22793ee6adb5324f6d7e67e4364de1a75491ecc3"
    url "https://github.com/joaofnds/trunk/releases/download/v0.47.5/Trunk_0.47.5_aarch64.dmg"
  end

  name "Trunk"
  desc "Desktop Git GUI"
  homepage "https://github.com/joaofnds/trunk"

  app "Trunk.app"
  binary "#{appdir}/Trunk.app/Contents/MacOS/trunk"

  postflight do
    system_command "/usr/bin/xattr",
                   args: ["-cr", "#{appdir}/Trunk.app"]
  end

  zap trash: [
    "~/Library/Application Support/com.joaofnds.trunk",
    "~/Library/Caches/com.joaofnds.trunk",
    "~/Library/WebKit/com.joaofnds.trunk",
  ]
end
