# Generated by joaofnds/trunk release workflow. DO NOT EDIT.
cask "trunk" do
  version "0.43.1"

  on_intel do
    sha256 "de883f547bfe24650d9cb8c45deddbfd32c69a6488f844a9380548b0131ee45e"
    url "https://github.com/joaofnds/trunk/releases/download/v#{version}/Trunk_0.12.8_x64.dmg"
  end
  on_arm do
    sha256 "0c65800fd9f695cbe308aa44b4bce4c3188c3abc4a46d4df66c350814bc1acc6"
    url "https://github.com/joaofnds/trunk/releases/download/v#{version}/Trunk_0.12.8_aarch64.dmg"
  end

  name "Trunk"
  desc "Desktop Git GUI"
  homepage "https://github.com/joaofnds/trunk"

  app "Trunk.app"

  postflight do
    system_command "/usr/bin/xattr",
                   args: ["-cr", "#{appdir}/Trunk.app"]
  end

  zap trash: [
    "~/Library/Application Support/com.joaofnds.trunk",
    "~/Library/Caches/com.joaofnds.trunk",
    "~/Library/WebKit/com.joaofnds.trunk",
  ]
end
