# Generated by joaofnds/trunk release workflow. DO NOT EDIT.
cask "trunk@0.53.2" do
  version "0.53.2"

  on_intel do
    sha256 "18c44d709c17281bfb1527e7546d19dccd3607d09c7ad26ae3e1f4f50473b33f"
    url "https://github.com/joaofnds/trunk/releases/download/v0.53.2/Trunk_0.53.2_x64.dmg"
  end
  on_arm do
    sha256 "53162b1b46136e5086b1f7ac13e4d1a2c491b4739118b5a6cdabfd3bfce4c3b3"
    url "https://github.com/joaofnds/trunk/releases/download/v0.53.2/Trunk_0.53.2_aarch64.dmg"
  end

  name "Trunk"
  desc "Desktop Git GUI"
  homepage "https://github.com/joaofnds/trunk"

  app "Trunk.app"
  binary "#{appdir}/Trunk.app/Contents/MacOS/trunk"

  postflight_steps do
    run "/usr/bin/xattr", args: ["-cr", "{{appdir}}/Trunk.app"]
  end

  zap trash: [
    "~/Library/Application Support/com.joaofnds.trunk",
    "~/Library/Caches/com.joaofnds.trunk",
    "~/Library/WebKit/com.joaofnds.trunk",
  ]
end
