# Generated by joaofnds/trunk release workflow. DO NOT EDIT.
cask "trunk@0.45.1" do
  version "0.45.1"

  on_intel do
    sha256 "6e13305101a59d4e2de88822b9d01f9ff42466dee9d51693058b095f18473c9d"
    url "https://github.com/joaofnds/trunk/releases/download/v0.45.1/Trunk_0.45.1_x64.dmg"
  end
  on_arm do
    sha256 "017ab3e94e9252b646283068929efece1e430b0042462779fc198c62d1902d17"
    url "https://github.com/joaofnds/trunk/releases/download/v0.45.1/Trunk_0.45.1_aarch64.dmg"
  end

  name "Trunk"
  desc "Desktop Git GUI"
  homepage "https://github.com/joaofnds/trunk"

  app "Trunk.app"
  binary "#{appdir}/Trunk.app/Contents/MacOS/trunk"

  postflight_steps do
    run "/usr/bin/xattr", args: ["-cr", "{{appdir}}/Trunk.app"]
  end

  zap trash: [
    "~/Library/Application Support/com.joaofnds.trunk",
    "~/Library/Caches/com.joaofnds.trunk",
    "~/Library/WebKit/com.joaofnds.trunk",
  ]
end
