# Generated by joaofnds/trunk release workflow. DO NOT EDIT.
cask "trunk@0.53.1" do
  version "0.53.1"

  on_intel do
    sha256 "6108e31f832d390b5318e6af574fe29ec5bfb28cf1ed281c6032dfafe2789504"
    url "https://github.com/joaofnds/trunk/releases/download/v0.53.1/Trunk_0.53.1_x64.dmg"
  end
  on_arm do
    sha256 "0c698fa960ac94176476dc808d76406d09e68116cdf2f655d01d70ed25643fc2"
    url "https://github.com/joaofnds/trunk/releases/download/v0.53.1/Trunk_0.53.1_aarch64.dmg"
  end

  name "Trunk"
  desc "Desktop Git GUI"
  homepage "https://github.com/joaofnds/trunk"

  app "Trunk.app"
  binary "#{appdir}/Trunk.app/Contents/MacOS/trunk"

  postflight_steps do
    run "/usr/bin/xattr", args: ["-cr", "{{appdir}}/Trunk.app"]
  end

  zap trash: [
    "~/Library/Application Support/com.joaofnds.trunk",
    "~/Library/Caches/com.joaofnds.trunk",
    "~/Library/WebKit/com.joaofnds.trunk",
  ]
end
