# Generated by joaofnds/trunk release workflow. DO NOT EDIT.
cask "trunk@0.48.1" do
  version "0.48.1"

  on_intel do
    sha256 "4197af657433c7cd57f70341035018b7bb18b48932c73d6b20d617579867d4a4"
    url "https://github.com/joaofnds/trunk/releases/download/v0.48.1/Trunk_0.48.1_x64.dmg"
  end
  on_arm do
    sha256 "e9dd423a284d73c8389dcca39c901218de0bf59cde233f2093cb7c15f5fe10a5"
    url "https://github.com/joaofnds/trunk/releases/download/v0.48.1/Trunk_0.48.1_aarch64.dmg"
  end

  name "Trunk"
  desc "Desktop Git GUI"
  homepage "https://github.com/joaofnds/trunk"

  app "Trunk.app"
  binary "#{appdir}/Trunk.app/Contents/MacOS/trunk"

  postflight do
    system_command "/usr/bin/xattr",
                   args: ["-cr", "#{appdir}/Trunk.app"]
  end

  zap trash: [
    "~/Library/Application Support/com.joaofnds.trunk",
    "~/Library/Caches/com.joaofnds.trunk",
    "~/Library/WebKit/com.joaofnds.trunk",
  ]
end
