# Generated by joaofnds/trunk release workflow. DO NOT EDIT.
cask "trunk@0.47.1" do
  version "0.47.1"

  on_intel do
    sha256 "7ee7d377e5b8880c9fc7c66205d9856c0cc64e084b51aab92ef8c06e1dad0410"
    url "https://github.com/joaofnds/trunk/releases/download/v0.47.1/Trunk_0.47.1_x64.dmg"
  end
  on_arm do
    sha256 "536d9771ec601e1bf2a63c00b889cf5c1cc597127e1927728c15f834c2e20fd6"
    url "https://github.com/joaofnds/trunk/releases/download/v0.47.1/Trunk_0.47.1_aarch64.dmg"
  end

  name "Trunk"
  desc "Desktop Git GUI"
  homepage "https://github.com/joaofnds/trunk"

  app "Trunk.app"
  binary "#{appdir}/Trunk.app/Contents/MacOS/trunk"

  postflight_steps do
    run "/usr/bin/xattr", args: ["-cr", "{{appdir}}/Trunk.app"]
  end

  zap trash: [
    "~/Library/Application Support/com.joaofnds.trunk",
    "~/Library/Caches/com.joaofnds.trunk",
    "~/Library/WebKit/com.joaofnds.trunk",
  ]
end
