# Generated by joaofnds/trunk release workflow. DO NOT EDIT.
cask "trunk@0.48.0" do
  version "0.48.0"

  on_intel do
    sha256 "e43f37c3fb21f5c4d88c093245a27226dd2ab49788a532d55641d306295e21a7"
    url "https://github.com/joaofnds/trunk/releases/download/v0.48.0/Trunk_0.47.5_x64.dmg"
  end
  on_arm do
    sha256 "c54e20e885601d0414d85805ad982ce6331f448774c3f968c7d60cd2dee4c4fe"
    url "https://github.com/joaofnds/trunk/releases/download/v0.48.0/Trunk_0.47.5_aarch64.dmg"
  end

  name "Trunk"
  desc "Desktop Git GUI"
  homepage "https://github.com/joaofnds/trunk"

  app "Trunk.app"
  binary "#{appdir}/Trunk.app/Contents/MacOS/trunk"

  postflight_steps do
    run "/usr/bin/xattr", args: ["-cr", "{{appdir}}/Trunk.app"]
  end

  zap trash: [
    "~/Library/Application Support/com.joaofnds.trunk",
    "~/Library/Caches/com.joaofnds.trunk",
    "~/Library/WebKit/com.joaofnds.trunk",
  ]
end
