# Generated by joaofnds/trunk release workflow. DO NOT EDIT.
cask "trunk" do
  version "0.25.0"

  on_intel do
    sha256 "d7ef3e90f62296bb83308fab3cb3f6005a18c81383b5e558f5cc840d64ee0e92"
    url "https://github.com/joaofnds/trunk/releases/download/v#{version}/trunk_0.12.8_x64.dmg"
  end
  on_arm do
    sha256 "69e65fe74fd1b0b66b618331da5dd36699db76397d3f6fc8840a42d62d4a272c"
    url "https://github.com/joaofnds/trunk/releases/download/v#{version}/trunk_0.12.8_aarch64.dmg"
  end

  name "Trunk"
  desc "Desktop Git GUI"
  homepage "https://github.com/joaofnds/trunk"

  app "trunk.app"

  postflight do
    system_command "/usr/bin/xattr",
                   args: ["-cr", "#{appdir}/trunk.app"]
  end

  zap trash: [
    "~/Library/Application Support/com.joaofnds.trunk",
    "~/Library/Caches/com.joaofnds.trunk",
    "~/Library/WebKit/com.joaofnds.trunk",
  ]
end
