# Generated by joaofnds/trunk release workflow. DO NOT EDIT.
cask "trunk@0.53.4" do
  version "0.53.4"

  on_intel do
    sha256 "aca9d4f4e6e4bd616da7e3a29e3ec4f3559ffe1e650083190a441d931350d08a"
    url "https://github.com/joaofnds/trunk/releases/download/v0.53.4/Trunk_0.53.4_x64.dmg"
  end
  on_arm do
    sha256 "343b8a3865cbe5ce8a6cc192da43765d90ddf7edee94c23d47d44c444bbc6cc7"
    url "https://github.com/joaofnds/trunk/releases/download/v0.53.4/Trunk_0.53.4_aarch64.dmg"
  end

  name "Trunk"
  desc "Desktop Git GUI"
  homepage "https://github.com/joaofnds/trunk"

  app "Trunk.app"
  binary "#{appdir}/Trunk.app/Contents/MacOS/trunk"

  postflight_steps do
    run "/usr/bin/xattr", args: ["-cr", "{{appdir}}/Trunk.app"]
  end

  zap trash: [
    "~/Library/Application Support/com.joaofnds.trunk",
    "~/Library/Caches/com.joaofnds.trunk",
    "~/Library/WebKit/com.joaofnds.trunk",
  ]
end
