# Generated by joaofnds/trunk release workflow. DO NOT EDIT.
cask "trunk@0.49.0" do
  version "0.49.0"

  on_intel do
    sha256 "014e8ada1bb48ab3086c6863847d0f5976f36f0d5b4bc40fb2641b5878644e23"
    url "https://github.com/joaofnds/trunk/releases/download/v0.49.0/Trunk_0.49.0_x64.dmg"
  end
  on_arm do
    sha256 "8c4daa884991f2e44f73b1bc56bc59772b96328c42af7ccd293eb8e053680462"
    url "https://github.com/joaofnds/trunk/releases/download/v0.49.0/Trunk_0.49.0_aarch64.dmg"
  end

  name "Trunk"
  desc "Desktop Git GUI"
  homepage "https://github.com/joaofnds/trunk"

  app "Trunk.app"
  binary "#{appdir}/Trunk.app/Contents/MacOS/trunk"

  postflight do
    system_command "/usr/bin/xattr",
                   args: ["-cr", "#{appdir}/Trunk.app"]
  end

  zap trash: [
    "~/Library/Application Support/com.joaofnds.trunk",
    "~/Library/Caches/com.joaofnds.trunk",
    "~/Library/WebKit/com.joaofnds.trunk",
  ]
end
