# Generated by joaofnds/trunk release workflow. DO NOT EDIT.
cask "trunk@0.50.0" do
  version "0.50.0"

  on_intel do
    sha256 "46bf9ad5fa9f8d21d96e037fe93044ba6750855bd4ef99769c32656f33f1b74d"
    url "https://github.com/joaofnds/trunk/releases/download/v0.50.0/Trunk_0.50.0_x64.dmg"
  end
  on_arm do
    sha256 "c8888ed2feee023d480d9939263421c2ed03e30bb5bc1975012583fe4587cabd"
    url "https://github.com/joaofnds/trunk/releases/download/v0.50.0/Trunk_0.50.0_aarch64.dmg"
  end

  name "Trunk"
  desc "Desktop Git GUI"
  homepage "https://github.com/joaofnds/trunk"

  app "Trunk.app"
  binary "#{appdir}/Trunk.app/Contents/MacOS/trunk"

  postflight do
    system_command "/usr/bin/xattr",
                   args: ["-cr", "#{appdir}/Trunk.app"]
  end

  zap trash: [
    "~/Library/Application Support/com.joaofnds.trunk",
    "~/Library/Caches/com.joaofnds.trunk",
    "~/Library/WebKit/com.joaofnds.trunk",
  ]
end
