# Generated by joaofnds/trunk release workflow. DO NOT EDIT.
cask "trunk@0.48.2" do
  version "0.48.2"

  on_intel do
    sha256 "34a288368c5198192ce6fae0af7659228c20148ab9f643297eccf8551750fb76"
    url "https://github.com/joaofnds/trunk/releases/download/v0.48.2/Trunk_0.48.2_x64.dmg"
  end
  on_arm do
    sha256 "aa8e73a7eade9b5f1cd730368ed97a5143603c481d5c5ec9fdf5f1213437e514"
    url "https://github.com/joaofnds/trunk/releases/download/v0.48.2/Trunk_0.48.2_aarch64.dmg"
  end

  name "Trunk"
  desc "Desktop Git GUI"
  homepage "https://github.com/joaofnds/trunk"

  app "Trunk.app"
  binary "#{appdir}/Trunk.app/Contents/MacOS/trunk"

  postflight do
    system_command "/usr/bin/xattr",
                   args: ["-cr", "#{appdir}/Trunk.app"]
  end

  zap trash: [
    "~/Library/Application Support/com.joaofnds.trunk",
    "~/Library/Caches/com.joaofnds.trunk",
    "~/Library/WebKit/com.joaofnds.trunk",
  ]
end
