# Generated by joaofnds/trunk release workflow. DO NOT EDIT.
cask "trunk@0.55.0" do
  version "0.55.0"

  on_intel do
    sha256 "0f255268c18884e42c5c722a4b43e8692bd1129b6314d71a8b768560204f1dd7"
    url "https://github.com/joaofnds/trunk/releases/download/v0.55.0/Trunk_0.55.0_x64.dmg"
  end
  on_arm do
    sha256 "9fec462f4740b265079096b5bf6ff901d3004e1be041dd31f0c6e7bea71093fc"
    url "https://github.com/joaofnds/trunk/releases/download/v0.55.0/Trunk_0.55.0_aarch64.dmg"
  end

  name "Trunk"
  desc "Desktop Git GUI"
  homepage "https://github.com/joaofnds/trunk"

  app "Trunk.app"
  binary "#{appdir}/Trunk.app/Contents/MacOS/trunk"

  postflight_steps do
    run "/usr/bin/xattr", args: ["-cr", "{{appdir}}/Trunk.app"]
  end

  zap trash: [
    "~/Library/Application Support/com.joaofnds.trunk",
    "~/Library/Caches/com.joaofnds.trunk",
    "~/Library/WebKit/com.joaofnds.trunk",
  ]
end
