# Generated by joaofnds/trunk release workflow. DO NOT EDIT.
cask "trunk@0.51.0" do
  version "0.51.0"

  on_intel do
    sha256 "71e0d6bcc6babe52e202dc93bfc9d17d01d338a64505b327258fb197d64a8053"
    url "https://github.com/joaofnds/trunk/releases/download/v0.51.0/Trunk_0.51.0_x64.dmg"
  end
  on_arm do
    sha256 "39837494888d7a01c21c8fa157ed63eedbbcc26bad8259fa92018d77cdffc2f4"
    url "https://github.com/joaofnds/trunk/releases/download/v0.51.0/Trunk_0.51.0_aarch64.dmg"
  end

  name "Trunk"
  desc "Desktop Git GUI"
  homepage "https://github.com/joaofnds/trunk"

  app "Trunk.app"
  binary "#{appdir}/Trunk.app/Contents/MacOS/trunk"

  postflight do
    system_command "/usr/bin/xattr",
                   args: ["-cr", "#{appdir}/Trunk.app"]
  end

  zap trash: [
    "~/Library/Application Support/com.joaofnds.trunk",
    "~/Library/Caches/com.joaofnds.trunk",
    "~/Library/WebKit/com.joaofnds.trunk",
  ]
end
