# Generated by joaofnds/trunk release workflow. DO NOT EDIT.
cask "trunk@0.52.1" do
  version "0.52.1"

  on_intel do
    sha256 "d352137d5ea3dae8e243c5f9827e4ec023fb6ad7e9b0ba1a9babd91332252c96"
    url "https://github.com/joaofnds/trunk/releases/download/v0.52.1/Trunk_0.52.1_x64.dmg"
  end
  on_arm do
    sha256 "a613636a58056f75d8f1de2c50bb7b539361a8af18940a7721407d73e8b2a1fb"
    url "https://github.com/joaofnds/trunk/releases/download/v0.52.1/Trunk_0.52.1_aarch64.dmg"
  end

  name "Trunk"
  desc "Desktop Git GUI"
  homepage "https://github.com/joaofnds/trunk"

  app "Trunk.app"
  binary "#{appdir}/Trunk.app/Contents/MacOS/trunk"

  postflight do
    system_command "/usr/bin/xattr",
                   args: ["-cr", "#{appdir}/Trunk.app"]
  end

  zap trash: [
    "~/Library/Application Support/com.joaofnds.trunk",
    "~/Library/Caches/com.joaofnds.trunk",
    "~/Library/WebKit/com.joaofnds.trunk",
  ]
end
