# Generated by joaofnds/trunk release workflow. DO NOT EDIT.
cask "trunk@0.53.3" do
  version "0.53.3"

  on_intel do
    sha256 "f0f6680a2a711672dfd92e67c80ecdadce3768b2ea47385e96e99e0999062bd7"
    url "https://github.com/joaofnds/trunk/releases/download/v0.53.3/Trunk_0.53.3_x64.dmg"
  end
  on_arm do
    sha256 "3b2c676e2fd2e119a4e3128012b1accc8effbe4719f02bc5ce0e9933d7f9f732"
    url "https://github.com/joaofnds/trunk/releases/download/v0.53.3/Trunk_0.53.3_aarch64.dmg"
  end

  name "Trunk"
  desc "Desktop Git GUI"
  homepage "https://github.com/joaofnds/trunk"

  app "Trunk.app"
  binary "#{appdir}/Trunk.app/Contents/MacOS/trunk"

  postflight_steps do
    run "/usr/bin/xattr", args: ["-cr", "{{appdir}}/Trunk.app"]
  end

  zap trash: [
    "~/Library/Application Support/com.joaofnds.trunk",
    "~/Library/Caches/com.joaofnds.trunk",
    "~/Library/WebKit/com.joaofnds.trunk",
  ]
end
