# Generated by joaofnds/trunk release workflow. DO NOT EDIT.
cask "trunk@0.56.2" do
  version "0.56.2"

  on_intel do
    sha256 "5862d7a904d196e1115bb75e99e8be784669c90367b05bb411a53d96cfe46109"
    url "https://github.com/joaofnds/trunk/releases/download/v0.56.2/Trunk_0.56.2_x64.dmg"
  end
  on_arm do
    sha256 "18e63f8bff0dd8c17eee98630bbf748845bccbda77209640f4f7cca57ba4dfe3"
    url "https://github.com/joaofnds/trunk/releases/download/v0.56.2/Trunk_0.56.2_aarch64.dmg"
  end

  name "Trunk"
  desc "Desktop Git GUI"
  homepage "https://github.com/joaofnds/trunk"

  app "Trunk.app"
  binary "#{appdir}/Trunk.app/Contents/MacOS/trunk"

  postflight_steps do
    run "/usr/bin/xattr", args: ["-cr", "{{appdir}}/Trunk.app"]
  end

  zap trash: [
    "~/Library/Application Support/com.joaofnds.trunk",
    "~/Library/Caches/com.joaofnds.trunk",
    "~/Library/WebKit/com.joaofnds.trunk",
  ]
end
