# Generated by joaofnds/trunk release workflow. DO NOT EDIT.
cask "trunk" do
  version "0.41.0"

  on_intel do
    sha256 "378ade78c5bce2e7693b13b4ac2bcf8766829cd0babf4a9111099e4bb136d9af"
    url "https://github.com/joaofnds/trunk/releases/download/v#{version}/trunk_0.12.8_x64.dmg"
  end
  on_arm do
    sha256 "d0a12229392bc2d5a987a65a7a8ea41fc0fb5a257f679396bd75631cbc453263"
    url "https://github.com/joaofnds/trunk/releases/download/v#{version}/trunk_0.12.8_aarch64.dmg"
  end

  name "Trunk"
  desc "Desktop Git GUI"
  homepage "https://github.com/joaofnds/trunk"

  app "trunk.app"

  postflight do
    system_command "/usr/bin/xattr",
                   args: ["-cr", "#{appdir}/trunk.app"]
  end

  zap trash: [
    "~/Library/Application Support/com.joaofnds.trunk",
    "~/Library/Caches/com.joaofnds.trunk",
    "~/Library/WebKit/com.joaofnds.trunk",
  ]
end
