# Generated by joaofnds/trunk release workflow. DO NOT EDIT.
cask "trunk@0.54.1" do
  version "0.54.1"

  on_intel do
    sha256 "1431b339e234e6dc43c148aa6e3808206154fa77b4949179b3e2b5279af6dde7"
    url "https://github.com/joaofnds/trunk/releases/download/v0.54.1/Trunk_0.54.0_x64.dmg"
  end
  on_arm do
    sha256 "2fc44b304f91cd08270127dda3639d6f1b90322ea33f7d77a1a46b8def6e035d"
    url "https://github.com/joaofnds/trunk/releases/download/v0.54.1/Trunk_0.54.0_aarch64.dmg"
  end

  name "Trunk"
  desc "Desktop Git GUI"
  homepage "https://github.com/joaofnds/trunk"

  app "Trunk.app"
  binary "#{appdir}/Trunk.app/Contents/MacOS/trunk"

  postflight_steps do
    run "/usr/bin/xattr", args: ["-cr", "{{appdir}}/Trunk.app"]
  end

  zap trash: [
    "~/Library/Application Support/com.joaofnds.trunk",
    "~/Library/Caches/com.joaofnds.trunk",
    "~/Library/WebKit/com.joaofnds.trunk",
  ]
end
