# Generated by joaofnds/trunk release workflow. DO NOT EDIT.
cask "trunk@0.47.3" do
  version "0.47.3"

  on_intel do
    sha256 "0521d350dbea9bc0bb85bfd29f1d1987a21821cf893bd63ae7e7e9b8b03d6e7d"
    url "https://github.com/joaofnds/trunk/releases/download/v0.47.3/Trunk_0.47.3_x64.dmg"
  end
  on_arm do
    sha256 "18ae682859931a60caef100462571c7f13acb403215e6df75d4005985165b9af"
    url "https://github.com/joaofnds/trunk/releases/download/v0.47.3/Trunk_0.47.3_aarch64.dmg"
  end

  name "Trunk"
  desc "Desktop Git GUI"
  homepage "https://github.com/joaofnds/trunk"

  app "Trunk.app"
  binary "#{appdir}/Trunk.app/Contents/MacOS/trunk"

  postflight_steps do
    run "/usr/bin/xattr", args: ["-cr", "{{appdir}}/Trunk.app"]
  end

  zap trash: [
    "~/Library/Application Support/com.joaofnds.trunk",
    "~/Library/Caches/com.joaofnds.trunk",
    "~/Library/WebKit/com.joaofnds.trunk",
  ]
end
