# Generated by joaofnds/trunk release workflow. DO NOT EDIT.
cask "trunk@0.47.4" do
  version "0.47.4"

  on_intel do
    sha256 "d7117eac1df5209272299fc62b99b02f403d0633217b6cdf50bedbd5e019a62a"
    url "https://github.com/joaofnds/trunk/releases/download/v0.47.4/Trunk_0.47.4_x64.dmg"
  end
  on_arm do
    sha256 "984534f3306d1ef85a6278b360c2d52f2dc1b2499d0680c4fdeca69b93ae5f4a"
    url "https://github.com/joaofnds/trunk/releases/download/v0.47.4/Trunk_0.47.4_aarch64.dmg"
  end

  name "Trunk"
  desc "Desktop Git GUI"
  homepage "https://github.com/joaofnds/trunk"

  app "Trunk.app"
  binary "#{appdir}/Trunk.app/Contents/MacOS/trunk"

  postflight_steps do
    run "/usr/bin/xattr", args: ["-cr", "{{appdir}}/Trunk.app"]
  end

  zap trash: [
    "~/Library/Application Support/com.joaofnds.trunk",
    "~/Library/Caches/com.joaofnds.trunk",
    "~/Library/WebKit/com.joaofnds.trunk",
  ]
end
