# Generated by joaofnds/trunk release workflow. DO NOT EDIT.
cask "trunk@0.48.3" do
  version "0.48.3"

  on_intel do
    sha256 "5396924a3a142d3bdbb8c0fca83d34ce2a08d024c12a9c33c072d1aee6838196"
    url "https://github.com/joaofnds/trunk/releases/download/v0.48.3/Trunk_0.48.3_x64.dmg"
  end
  on_arm do
    sha256 "3784c3cc3b42f62f0562cf551c1319d91123b12fd1471691576adc0091f66c6a"
    url "https://github.com/joaofnds/trunk/releases/download/v0.48.3/Trunk_0.48.3_aarch64.dmg"
  end

  name "Trunk"
  desc "Desktop Git GUI"
  homepage "https://github.com/joaofnds/trunk"

  app "Trunk.app"
  binary "#{appdir}/Trunk.app/Contents/MacOS/trunk"

  postflight_steps do
    run "/usr/bin/xattr", args: ["-cr", "{{appdir}}/Trunk.app"]
  end

  zap trash: [
    "~/Library/Application Support/com.joaofnds.trunk",
    "~/Library/Caches/com.joaofnds.trunk",
    "~/Library/WebKit/com.joaofnds.trunk",
  ]
end
