# Generated by joaofnds/trunk release workflow. DO NOT EDIT.
cask "trunk@0.54.0" do
  version "0.54.0"

  on_intel do
    sha256 "168cac7f1b774f1224a834231379b96a125184725a0f1b99146f7e8df77db824"
    url "https://github.com/joaofnds/trunk/releases/download/v0.54.0/Trunk_0.54.0_x64.dmg"
  end
  on_arm do
    sha256 "1322f6c740c82e6e79857596ae653b8d524541b7c91b9833e608773f3fd96238"
    url "https://github.com/joaofnds/trunk/releases/download/v0.54.0/Trunk_0.54.0_aarch64.dmg"
  end

  name "Trunk"
  desc "Desktop Git GUI"
  homepage "https://github.com/joaofnds/trunk"

  app "Trunk.app"
  binary "#{appdir}/Trunk.app/Contents/MacOS/trunk"

  postflight_steps do
    run "/usr/bin/xattr", args: ["-cr", "{{appdir}}/Trunk.app"]
  end

  zap trash: [
    "~/Library/Application Support/com.joaofnds.trunk",
    "~/Library/Caches/com.joaofnds.trunk",
    "~/Library/WebKit/com.joaofnds.trunk",
  ]
end
