# Generated by joaofnds/trunk release workflow. DO NOT EDIT.
cask "trunk@0.53.0" do
  version "0.53.0"

  on_intel do
    sha256 "0419da3984648e7ffc6f411099e243a729f701a1947845358c62800bde1c141d"
    url "https://github.com/joaofnds/trunk/releases/download/v0.53.0/Trunk_0.53.0_x64.dmg"
  end
  on_arm do
    sha256 "b534fec3786ff0bfdd9a234b938062448df5d230adf473a01195ca8539bae24a"
    url "https://github.com/joaofnds/trunk/releases/download/v0.53.0/Trunk_0.53.0_aarch64.dmg"
  end

  name "Trunk"
  desc "Desktop Git GUI"
  homepage "https://github.com/joaofnds/trunk"

  app "Trunk.app"
  binary "#{appdir}/Trunk.app/Contents/MacOS/trunk"

  postflight_steps do
    run "/usr/bin/xattr", args: ["-cr", "{{appdir}}/Trunk.app"]
  end

  zap trash: [
    "~/Library/Application Support/com.joaofnds.trunk",
    "~/Library/Caches/com.joaofnds.trunk",
    "~/Library/WebKit/com.joaofnds.trunk",
  ]
end
