# Generated by joaofnds/trunk release workflow. DO NOT EDIT.
cask "trunk@0.56.1" do
  version "0.56.1"

  on_intel do
    sha256 "3df58586fac00eb26387a6cb1ece7c471d8ac7a4ae8366096e70969de06b0954"
    url "https://github.com/joaofnds/trunk/releases/download/v0.56.1/Trunk_0.56.1_x64.dmg"
  end
  on_arm do
    sha256 "c905599c4f2879bc33018237d07fed3236b7d07569eb89f15286e82c2d43d822"
    url "https://github.com/joaofnds/trunk/releases/download/v0.56.1/Trunk_0.56.1_aarch64.dmg"
  end

  name "Trunk"
  desc "Desktop Git GUI"
  homepage "https://github.com/joaofnds/trunk"

  app "Trunk.app"
  binary "#{appdir}/Trunk.app/Contents/MacOS/trunk"

  postflight_steps do
    run "/usr/bin/xattr", args: ["-cr", "{{appdir}}/Trunk.app"]
  end

  zap trash: [
    "~/Library/Application Support/com.joaofnds.trunk",
    "~/Library/Caches/com.joaofnds.trunk",
    "~/Library/WebKit/com.joaofnds.trunk",
  ]
end
