# Generated by joaofnds/trunk release workflow. DO NOT EDIT.
cask "trunk@0.47.0" do
  version "0.47.0"

  on_intel do
    sha256 "3f1a348b0e6dbfddb999453cc13a3f44b85531b43abd02ee269943db2e2b0999"
    url "https://github.com/joaofnds/trunk/releases/download/v0.47.0/Trunk_0.47.0_x64.dmg"
  end
  on_arm do
    sha256 "551f395376c6fcfcac81a038a6af503df5bed5fbc2167f16b7345bc14828d1ec"
    url "https://github.com/joaofnds/trunk/releases/download/v0.47.0/Trunk_0.47.0_aarch64.dmg"
  end

  name "Trunk"
  desc "Desktop Git GUI"
  homepage "https://github.com/joaofnds/trunk"

  app "Trunk.app"
  binary "#{appdir}/Trunk.app/Contents/MacOS/trunk"

  postflight_steps do
    run "/usr/bin/xattr", args: ["-cr", "{{appdir}}/Trunk.app"]
  end

  zap trash: [
    "~/Library/Application Support/com.joaofnds.trunk",
    "~/Library/Caches/com.joaofnds.trunk",
    "~/Library/WebKit/com.joaofnds.trunk",
  ]
end
