# Generated by joaofnds/trunk release workflow. DO NOT EDIT.
cask "trunk@0.46.0" do
  version "0.46.0"

  on_intel do
    sha256 "08f5670b4bb7124d46793fb2e41e2fcc7731f081db27f84028070231e2b4a2c0"
    url "https://github.com/joaofnds/trunk/releases/download/v0.46.0/Trunk_0.46.0_x64.dmg"
  end
  on_arm do
    sha256 "242208c5fdfdcb9da3f98b7de0da2763f97ac101bfa667f91f6d5fec303d4323"
    url "https://github.com/joaofnds/trunk/releases/download/v0.46.0/Trunk_0.46.0_aarch64.dmg"
  end

  name "Trunk"
  desc "Desktop Git GUI"
  homepage "https://github.com/joaofnds/trunk"

  app "Trunk.app"
  binary "#{appdir}/Trunk.app/Contents/MacOS/trunk"

  postflight do
    system_command "/usr/bin/xattr",
                   args: ["-cr", "#{appdir}/Trunk.app"]
  end

  zap trash: [
    "~/Library/Application Support/com.joaofnds.trunk",
    "~/Library/Caches/com.joaofnds.trunk",
    "~/Library/WebKit/com.joaofnds.trunk",
  ]
end
