# Generated by joaofnds/trunk release workflow. DO NOT EDIT.
cask "trunk@0.47.2" do
  version "0.47.2"

  on_intel do
    sha256 "1081ec75794ef63fc904b23bf2d995a07d01612278462445e8fe3e5adbf3d09e"
    url "https://github.com/joaofnds/trunk/releases/download/v0.47.2/Trunk_0.47.2_x64.dmg"
  end
  on_arm do
    sha256 "dc90a7f2e58909c71e55be850bcd39f0090575cc9854af13773cc94da4f70518"
    url "https://github.com/joaofnds/trunk/releases/download/v0.47.2/Trunk_0.47.2_aarch64.dmg"
  end

  name "Trunk"
  desc "Desktop Git GUI"
  homepage "https://github.com/joaofnds/trunk"

  app "Trunk.app"
  binary "#{appdir}/Trunk.app/Contents/MacOS/trunk"

  postflight do
    system_command "/usr/bin/xattr",
                   args: ["-cr", "#{appdir}/Trunk.app"]
  end

  zap trash: [
    "~/Library/Application Support/com.joaofnds.trunk",
    "~/Library/Caches/com.joaofnds.trunk",
    "~/Library/WebKit/com.joaofnds.trunk",
  ]
end
