# Generated by joaofnds/trunk release workflow. DO NOT EDIT.
cask "trunk@0.56.0" do
  version "0.56.0"

  on_intel do
    sha256 "b24fbf6d7350e2c99ac7e67caf7da99aa3d23c0e9b70bc8ea4de8eae19ee8d56"
    url "https://github.com/joaofnds/trunk/releases/download/v0.56.0/Trunk_0.56.0_x64.dmg"
  end
  on_arm do
    sha256 "b4745e3bdfa34a2acdd4e082e92efd42272d73f7d79e1157b3f585d9f09a5d6a"
    url "https://github.com/joaofnds/trunk/releases/download/v0.56.0/Trunk_0.56.0_aarch64.dmg"
  end

  name "Trunk"
  desc "Desktop Git GUI"
  homepage "https://github.com/joaofnds/trunk"

  app "Trunk.app"
  binary "#{appdir}/Trunk.app/Contents/MacOS/trunk"

  postflight_steps do
    run "/usr/bin/xattr", args: ["-cr", "{{appdir}}/Trunk.app"]
  end

  zap trash: [
    "~/Library/Application Support/com.joaofnds.trunk",
    "~/Library/Caches/com.joaofnds.trunk",
    "~/Library/WebKit/com.joaofnds.trunk",
  ]
end
