# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AsdfInstallLatest < Formula
  desc "asdf utility to update plugins to their latest version"
  homepage "https://github.com/joaofnds/asdf-install-latest"
  version "0.0.10"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/joaofnds/asdf-install-latest/releases/download/0.0.10/asdf-install-latest_0.0.10_darwin_amd64.tar.gz"
      sha256 "2f03bcea9b4d3cd979d9f30fbfe6300556d3fb4ef93b6c88875f53139a02a419"

      def install
        bin.install "asdf-install-latest"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/joaofnds/asdf-install-latest/releases/download/0.0.10/asdf-install-latest_0.0.10_darwin_arm64.tar.gz"
      sha256 "a5a36a6c057f2eedcd1e3c99aefde39089db5c43e58263c1d609f261f226ed8f"

      def install
        bin.install "asdf-install-latest"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/joaofnds/asdf-install-latest/releases/download/0.0.10/asdf-install-latest_0.0.10_linux_arm64.tar.gz"
      sha256 "7bdb776c595d87c33efeacdc2373552b7a7a115bbc0834e4685de28039e0720f"

      def install
        bin.install "asdf-install-latest"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/joaofnds/asdf-install-latest/releases/download/0.0.10/asdf-install-latest_0.0.10_linux_amd64.tar.gz"
      sha256 "7fbd4cada8894e071f109ce06a3deb6cbc54660e504c551fd0adf500cab93302"

      def install
        bin.install "asdf-install-latest"
      end
    end
  end
end
