# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Astro < Formula
  desc "a habit tracker for your terminal with a GitHub style activity graph"
  homepage "https://github.com/joaofnds/astro"
  version "0.0.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/joaofnds/astro/releases/download/0.0.4/astro_0.0.4_Darwin_arm64.tar.gz"
      sha256 "284d39d5bb08741fc974de9f67b1d97acbb793749e8e8f2f4049e43511ae4cf2"

      def install
        bin.install "astro"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/joaofnds/astro/releases/download/0.0.4/astro_0.0.4_Darwin_x86_64.tar.gz"
      sha256 "844b5a190bef2281706b95319abae71b50b39685b51f78d240d28b2366d92d48"

      def install
        bin.install "astro"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/joaofnds/astro/releases/download/0.0.4/astro_0.0.4_Linux_x86_64.tar.gz"
      sha256 "46eba20f27021f58b3ed2d83659718fc3f99d38addb9bbe0a272da2036d26be5"

      def install
        bin.install "astro"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/joaofnds/astro/releases/download/0.0.4/astro_0.0.4_Linux_arm64.tar.gz"
      sha256 "f7c2cc0d46a8e70a1c180d3ccba0954c1c2347b5b1276da55410f61b0713026f"

      def install
        bin.install "astro"
      end
    end
  end
end
