# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Astro < Formula
  desc "a habit tracker for your terminal with a GitHub style activity graph"
  homepage "https://github.com/joaofnds/astro"
  version "0.0.35"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/joaofnds/astro/releases/download/0.0.35/astro_0.0.35_Darwin_arm64.tar.gz"
      sha256 "286fd59d0060c8f208f285f1a4c0c7d8592565842ca0b3e4934018e5fa174cdc"

      def install
        bin.install "astro"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/joaofnds/astro/releases/download/0.0.35/astro_0.0.35_Darwin_x86_64.tar.gz"
      sha256 "5239cf69f958f5f84f2b37fc2d77a095237053a066340668aaf4e3863c112e46"

      def install
        bin.install "astro"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/joaofnds/astro/releases/download/0.0.35/astro_0.0.35_Linux_arm64.tar.gz"
      sha256 "710684b68d6b4d334a43cbc79b3d9b912f587af12fa713fe698fe2cca7713721"

      def install
        bin.install "astro"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/joaofnds/astro/releases/download/0.0.35/astro_0.0.35_Linux_x86_64.tar.gz"
      sha256 "770a9684f253d4d8d2f81ac081f1231de7d621cfdb2298c6873c20f1c250124d"

      def install
        bin.install "astro"
      end
    end
  end
end
